name: my-first-workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: windows-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!!!"
      - name: Print goodbye
        run: echo "ok...bye!!"
